# Generated by Django 4.1.13 on 2024-06-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='date_of_adventure',
        ),
    ]
